### ISSUE TITLE
FluidSynth Plugin Releases folder removed

### ISSUE THREAD

**Issue by FranticPlus** [prof-spock/FluidSynthPlugin#11]
Hi
I am trying to download the fluidsynth plugin for Windows from the releases folder at https://github.com/prof-spock/FluidSynthPlugin/blob/master/releases and it is not available.
Please let me know the correct folder or update your readme.
Thanks
Walter

**Comment by prof-spock** [comment]
Hello Walter,
thanks for the information! I shall update the readme file, it seems to be outdated.
The correct folder is [https://github.com/prof-spock/FluidSynthPlugin/releases](https://github.com/prof-spock/FluidSynthPlugin/releases)

Best regards,
Prof. Spock

**Comment by prof-spock** [comment]
part of release 0.7.0, see [release notes](https://github.com/prof-spock/FluidSynthPlugin/releases/tag/v0.7.0)
