### ISSUE TITLE
request: specify linked FluidSynth version in release information

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#12]
I would like to request that the version of FluidSynth included in each release be identified in the release info. This will be helpful for making synth/plugin recommendations when I release my SoundFonts as there are compatibility fixes committed in recent and upcoming FluidSynth versions that impact some of my work. Just to be sure I am using FluidSynthPlugin with the latest FluidSynth version, I have been using the library files from the latest FluidSynth binary release on the GitHub page (version 2.3.4, as 2.3.5 only has source files in the release assets), since I have no idea what version comes bundled with the plugin.

**Comment by prof-spock** [comment]
Hello mrbumpy409,

it seems you are very diligently testing the plugin, finding bugs and suggesting improvements.

In my long career as a software professional I have only found very few testers like that with that kind of dedication :wink:

Nevertheless I am hesitant to specify the versions of FluidSynth in the release documentation.  Of course, I provide the libraries as a starting point, but it has been a major design goal **to be able to update the FluidSynth functionality without having to update the FluidSynthPlugins regularly**. Hence the FluidSynth library is dynamically linked (as opposed to e.g. Alexey Zhelezov's FluidSynthVST).

If I were to specify the used versions, I would feel obliged to just put out another release whenever FluidSynth provides a new version.

And while one could currently build a FluidSynth version 2.3.5 yourself, unfortunately the currently provided Windows binary version is at 2.3.4, Ubuntu (APT) just provides a 2.2.6 version and MacOSX (MacPorts) a 2.3.4 version.

So this is a mess. To be absolutely consistent I would have to build the versions for all platforms myself at every FluidSynth update.

But what I now provided is an `About...` dialog in the context menu: here you can find the FluidSynth library version the plugin is currently using.  And you can provide your own library by kicking out the DLLs, DYLIBs or SOs from the plugin bundle and either use the system wide library or copy the libraries into the bundle.

I am not sure if this meets your requirements, but at least it tells you whether you need a new FluidSynth library version :wink:

Best regards,
Prof. Spock

**Comment by mrbumpy409** [comment]
Being able to see the version in "About..." is perfect. I will be recommending FluidSynthPlugin in the documentation for my upcoming SoundFonts, and I need to be able to advise my users if it becomes necessary to update the FluidSynth version separately. For example, one of the presets in my upcoming GeneralUser GS update won't sound correct in FluidSynth until version 2.4 is released (see [related bug report](https://github.com/FluidSynth/fluidsynth/issues/1312)). So, when the time comes, I can provide instructions for updating the library.

**Comment by prof-spock** [comment]
Hello mrbumpy409,

I have no problem providing the FluidSynth 2.4 version timely in the repository, if this helps :wink:

Maybe @derselbst (hi!) can both provide the Windows binary in the FluidSynth releases page and also ensure that the version is available in the Ubuntu stable repository and in MacPorts. But looking at the [installation page](https://github.com/FluidSynth/fluidsynth/wiki/Download#distributions) I am quite confident about the professionalism of that group...

They know me quite well over there and hope that I stay quiet and do not ask any esoterical questions... :grin:

Best regards,
Prof. Spock

**Comment by derselbst** [comment]
Oh, thanks for the hint. Publishing the binaries requires manually triggering a release pipeline in Azure DevOps, which I forgot this time. Will be fixed in a few minutes.

I am not the right guy for macPorts or Ubuntu. Though, I would assume it becomes available as soon as someone files a PR to them.

https://github.com/macports/macports-ports/pull/20646
https://salsa.debian.org/multimedia-team/fluidsynth/-/commits/master?ref_type=heads

---

> They know me quite well over there and hope that I stay quiet and do not ask any esoterical questions... 😁

Your telepathic skills are astonishing! :D

**Comment by prof-spock** [comment]
Hello @derselbst,

nice to hear from you!
> Oh, thanks for the hint. Publishing the binaries requires manually triggering a release pipeline in Azure DevOps, which I forgot this time. Will be fixed in a few minutes.

Of course, this was never meant as a criticism. I am always **fascinated** how professional the FluidSynth team handles software deployment.  I can learn a lot from you.

>>They know me quite well over there and hope that I stay quiet and do not ask any esoterical questions... 😁

>Your telepathic skills are astonishing! :D

Normally I would have to do my infamous mind-meld for that and then touch you. I'm sure you wouldn't want that...

Best regards,
Prof. Spock

**Comment by prof-spock** [comment]
part of release 0.7.0, see [release notes](https://github.com/prof-spock/FluidSynthPlugin/releases/tag/v0.7.0)
