### ISSUE TITLE
Releases missing linux vst3s for v0.7.0 onwards

### ISSUE THREAD

**Issue by row454** [prof-spock/FluidSynthPlugin#14]
The releases are missing linux vst3s for v0.7.0 onwards, I ended up compiling it from source instead

**Comment by prof-spock** [comment]
Hello row454,

sorry for your inconvenience and thanks for the hint!

There was an error in the distribution script that left out the Linux VST as well as several programs of the MacOS distribution. I have updated the 0.7.1 release files accordingly.

Best regards,
Prof. Spock

**Comment by prof-spock** [comment]
Hello row454,

the new release v0.7.5 removes any fluidsynth library for Linux from the distribution and instead requires a fluidsynth package installation; this is also described in the appendix of the [documentation](https://github.com/prof-spock/FluidSynthPlugin/blob/master/FluidSynthPlugin-documentation.pdf).

Hence the issue should be fixed now as soon as you have a fluidsynth package installation on you Linux system.

Please let me know, whether this is correct or not.

Best regards,
Prof. Spock
