### ISSUE TITLE
release v0.7.1 Windows VST3 right-click SoundFont & preset chooser not working properly

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#16]
If I use version 0.7.1 of the plugin for Windows downloaded from the GitHub release, FluidSynthPlugin's SoundFont and preset chooser both fail to set the appropriate text in the plugin window (tested in REAPER). If I choose a SoundFont, after clicking "Open", the following will appear in the text box:
```
 = /path/to/soundfont.sf2
```
Of course, this should instead be showing:
```
soundfont = /path/to/soundfont.sf2
```
After correcting the text by adding the missing "soundfont" key, then the preset browser exhibits the same problem. Selecting preset 003 adds the following to the text box:
```
 = 0:3
```
...but it is supposed to be showing:
```
preset = 0:3
```
I have created a video showing the problem: https://github.com/prof-spock/FluidSynthPlugin/assets/6825789/58c7d077-934e-4814-a6b9-80d02ee2565c

This problem does not occur if I compile FluidSynth Plugin from source.

**OS:** Windows 10 Professional (within VirtualBox) and Windows 10 Home (on a desktop PC)

**Comment by prof-spock** [comment]
Hello mrbumpy409,

sorry for the late answer, but I have been busy last week.

I can reproduce your findings; unfortunately those errors were hidden in my development system by another FluidSynth plugin version in the canonical search path (used elsewhere for testing purposes ☹️).

I have updated all platforms **without any functional changes**; please have a look at the Linux and Windows versions provided now.

Best regards,
Prof. Spock

**Comment by mrbumpy409** [comment]
Thanks, Prof. Spock! The Windows version now works correctly. The Linux version still fails to scan, however.
