### ISSUE TITLE
FluidSynth Plugin v0.7.1 reports itself as v0.7.0

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#18]
A minor bug, for sure, but I thought you should know that FluidSynth Plugin v0.7.1 is reporting itself as v0.7.0 in the plugin's "About" box.

**Comment by prof-spock** [comment]
Hello mrbumpy409,

the new release v0.7.5 should fix the above problem: the current version should be available in the "About"-dialog.

Please let me know, whether this is correct or not.

Best regards,
Prof. Spoc
