### ISSUE TITLE
Feature Request: "SoundFonts Path" global setting for saving VST3 chunk params with relative SF2 path for portability

### ISSUE THREAD

**Issue by gaabora** [prof-spock/FluidSynthPlugin#21]
Hello!
Thanks for the amazing work on this project!

I would like to request the addition of "SoundFonts Path" global setting. This would allow users to save VST3 parameters with a relative SF2 path instead of an absolute one. This feature would greatly enhance portability, making it easier to share projects across different systems without path issues.

Example usage: 
soundfont = "%sf2_path%/file.sf2"

so it resolve the path based on global setting (that is stored for example in a properties file)

Thank you for considering this request!

**Comment by prof-spock** [comment]
Hello gaabora,

thanks for your suggestion, but there is already a mechanism in place for that.

As described in the documentation you can use environment variables from your system within the soundfont path.
So if you are on Windows - as I assume from your example -, you can set the environment variable `sf2_path` (ideally permanently via the control panel) and then use the notation
`soundfont = ${sf2_path}/file.sf2`
within the FluidSynthPlugin.

This also works in other operating systems; so DAW project files are portable across those OSs as long as you set the environment variables correctly.

When you select the soundfont file in the plugin via the context menu, this substitution is automatically done.
Please check whether it works as described.

Best regards,
Prof. Spock

**Comment by gaabora** [comment]
Awesome! thank you!
