### ISSUE TITLE
saved VST presets don't include parameter text

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#5]
Saved VST presets (at least as they are saved in REAPER) do not preserve the parameter text typed into the FluidSynthPlugin GUI. However, this text is preserved when saved as an FX chain or when a plugin instance is attached to a track and the project is reloaded.

### Steps to Reproduce

1. Assign FluidSynthPlugin to a track in REAPER.
2. Add configuration text to load a preset from a SoundFont and hit "Confirm".
3. Click the + icon and select "Save preset...".
4. Give the preset a name and click "OK".
5. Remove FluidSynthPlugin from the track and re-add it.
6. Select your saved preset from the drop-down menu at the top of the plugin window.

### Actual Result

There is no text in the GUI input box. However, the plugin does play the previously configured sound when it receives MIDI input.

### Expected Result

The settings added in repro step 2 should be visible in the GUI.

**Comment by prof-spock** [comment]
Hello @mrbumpy409,

I can confirm that bug.
It will be fixed in the next release; it already works in my local version :wink:

Best regards,
Prof. Spock

**Comment by mrbumpy409** [comment]
I can confirm that this bug is now fixed. Thanks again! :smile:

**Comment by prof-spock** [comment]
closed as fixed
