### ISSUE TITLE
new GUI feature build: browse for preset when currently selected bank doesn't exist = crash

### ISSUE THREAD

**Issue by mrbumpy409** [prof-spock/FluidSynthPlugin#9]
Steps to reproduce:
1. Load a SoundFont into FluidSynth plugin and set the program line to a bank that doesn't exist in the SoundFont, e.g. `program = 120:0`
2. Right-click and choose "Select Program...".

Result: The plugin crashes.

**Comment by prof-spock** [comment]
Hello mrbumpy409,

this is absolutely a bug.  I assume this can be fixed easily :wink:

Best regards
Prof. Spock

**Comment by prof-spock** [comment]
Hello mrbumpy409,

I have added a check both in the program selection dialog and in the editor window itself.
So an unknown preset should not occur (hopefully).

Best regards
Prof. Spock

**Comment by mrbumpy409** [comment]
The crash is fixed now. Excellent! :grin:

**Comment by prof-spock** [comment]
part of release 0.7.0, see [release notes](https://github.com/prof-spock/FluidSynthPlugin/releases/tag/v0.7.0)
